export const CTA_TYPES = {
  GET_STARTED: "getStarted",
  START: "start",
  START_NOW: "startNow",
  START_FREE: "startFree",
  START_FREE_TRIAL: "startFreeTrial",
  TRY_FOR_FREE: "tryForFree",

  CREATE_ACCOUNT: "createAccount",
  SIGN_UP: "signUp",
  JOIN_NOW: "joinNow",

  CONTINUE: "continue",
  NEXT: "next",
  FINISH: "finish",
  SKIP: "skip",
  BACK: "back",

  SAVE: "save",
  SAVE_CHANGES: "saveChanges",
  UPDATE: "update",
  APPLY_CHANGES: "applyChanges",
  SUBMIT: "submit",
  SEND: "send",

  CONFIRM: "confirm",
  YES_CONTINUE: "yesContinue",
  CANCEL: "cancel",
  CLOSE: "close",
  DONE: "done",

  ADD: "add",
  ADD_NEW: "addNew",
  CREATE: "create",
  EDIT: "edit",
  DELETE: "delete",
  REMOVE: "remove",
  ARCHIVE: "archive",
  RESTORE: "restore",

  UPLOAD: "upload",
  DOWNLOAD: "download",
  EXPORT: "export",
  IMPORT: "import",

  VIEW: "view",
  VIEW_DETAILS: "viewDetails",
  VIEW_REPORT: "viewReport",
  VIEW_ALL: "viewAll",
  READ_MORE: "readMore",
  LEARN_MORE: "learnMore",
  SEE_HOW_IT_WORKS: "seeHowItWorks",
  WATCH_VIDEO: "watchVideo",

  OPEN: "open",
  OPEN_CHAT: "openChat",
  REPLY: "reply",
  MARK_AS_READ: "markAsRead",

  PIN: "pin",
  UNPIN: "unpin",
  SHARE: "share",
  COPY_LINK: "copyLink",
  INVITE: "invite",

  ACCEPT: "accept",
  DECLINE: "decline",
  APPROVE: "approve",
  REJECT: "reject",

  PAY_NOW: "payNow",
  CHECKOUT: "checkout",
  BUY_NOW: "buyNow",
  ADD_TO_CART: "addToCart",
  SUBSCRIBE: "subscribe",

  CLAIM_REWARD: "claimReward",
  REQUEST_SUPPORT: "requestSupport",
  CONTACT_US: "contactUs",
  BOOK_DEMO: "bookDemo",
  SCHEDULE_NOW: "scheduleNow",
  REGISTER_NOW: "registerNow",
};
